// social-feed: 한국어 + English canonical fixtures
class ProofStateFixture {
  const ProofStateFixture({required this.title, required this.body, required this.actionLabel, required this.recoveryLabel, required this.recoverTo, required this.kind, required this.busy, required this.blocksPrimary, required this.requiresAcknowledgement});
  final String title; final String body; final String actionLabel; final String recoveryLabel; final String? recoverTo; final String kind; final bool busy; final bool blocksPrimary; final bool requiresAcknowledgement;
}
const requiredStates = <String>['default','loading','empty','error','success','focused','enabled'];
const proofFixtures = <String, Map<String, String>>{
  'ko': {'title': '오늘의 커뮤니티', 'subtitle': '관심 있는 사람들의 새 소식을 편안하게 둘러보세요.', 'primary_cta': '새 글 쓰기', 'success_label': '작성 화면 열림', 'field_label': '게시물 작성', 'secondary_label': '댓글 24개', 'item_title': '지영 · 모바일 디자인', 'item_body': '작은 화면일수록 정보의 순서와 여백이 제품의 목소리를 더 또렷하게 만든다고 느꼈어요.', 'item_meta': '12분 전', 'amount': '', 'risk_notice': '', 'confirm_label': '', 'message_in': '', 'message_out': '', 'map_label': '', 'media_label': '보라색과 회색으로 구성된 모바일 UI 스터디 이미지', 'switch_language_label': '언어 전환'},
  'en': {'title': 'Today\'s community', 'subtitle': 'Browse new posts from people and topics you care about.', 'primary_cta': 'Write a post', 'success_label': 'Composer opened', 'field_label': 'Create post', 'secondary_label': '24 comments', 'item_title': 'Jiyoung · Mobile design', 'item_body': 'On a small screen, information order and spacing make the product voice much clearer.', 'item_meta': '12 min ago', 'amount': '', 'risk_notice': '', 'confirm_label': '', 'message_in': '', 'message_out': '', 'map_label': '', 'media_label': 'Purple and gray mobile UI study', 'switch_language_label': 'Switch language'},
};
const stateFixtures = <String, Map<String, ProofStateFixture>>{
  'ko': {'default': ProofStateFixture(title: '오늘의 커뮤니티', body: '관심 있는 사람들의 새 소식을 편안하게 둘러보세요.', actionLabel: '새 글 쓰기', recoveryLabel: '기본 상태로 돌아가기', recoverTo: null, kind: 'default', busy: false, blocksPrimary: false, requiresAcknowledgement: false), 'loading': ProofStateFixture(title: '화면을 준비하고 있어요', body: '네트워크 요청 없이 로컬 예시를 불러오고 있습니다.', actionLabel: '새 글 쓰기', recoveryLabel: '기본 상태로 돌아가기', recoverTo: null, kind: 'loading', busy: true, blocksPrimary: true, requiresAcknowledgement: false), 'empty': ProofStateFixture(title: '아직 내용이 없어요', body: '아래 기본 동작으로 시작해 보세요.', actionLabel: '새 글 쓰기', recoveryLabel: '기본 상태로 돌아가기', recoverTo: 'default', kind: 'empty', busy: false, blocksPrimary: true, requiresAcknowledgement: false), 'error': ProofStateFixture(title: '완료하지 못했어요', body: '표시된 정보를 확인하고 다시 시도해 주세요.', actionLabel: '새 글 쓰기', recoveryLabel: '기본 상태로 돌아가기', recoverTo: 'default', kind: 'error', busy: false, blocksPrimary: true, requiresAcknowledgement: false), 'success': ProofStateFixture(title: '완료됐어요', body: '로컬 작성 상태로 전환했습니다.', actionLabel: '작성 화면 열림', recoveryLabel: '기본 상태로 돌아가기', recoverTo: null, kind: 'success', busy: false, blocksPrimary: false, requiresAcknowledgement: false), 'focused': ProofStateFixture(title: '입력란을 선택했어요', body: '활성 입력란은 키보드 위에서 계속 보입니다.', actionLabel: '새 글 쓰기', recoveryLabel: '기본 상태로 돌아가기', recoverTo: null, kind: 'interaction', busy: false, blocksPrimary: false, requiresAcknowledgement: false), 'enabled': ProofStateFixture(title: '진행할 준비가 됐어요', body: '이 로컬 예시의 기본 동작을 사용할 수 있습니다.', actionLabel: '새 글 쓰기', recoveryLabel: '기본 상태로 돌아가기', recoverTo: null, kind: 'interaction', busy: false, blocksPrimary: false, requiresAcknowledgement: false)},
  'en': {'default': ProofStateFixture(title: 'Today\'s community', body: 'Browse new posts from people and topics you care about.', actionLabel: 'Write a post', recoveryLabel: 'Return to default', recoverTo: null, kind: 'default', busy: false, blocksPrimary: false, requiresAcknowledgement: false), 'loading': ProofStateFixture(title: 'Preparing your screen', body: 'The local example is loading without a network request.', actionLabel: 'Write a post', recoveryLabel: 'Return to default', recoverTo: null, kind: 'loading', busy: true, blocksPrimary: true, requiresAcknowledgement: false), 'empty': ProofStateFixture(title: 'Nothing here yet', body: 'Start with the primary action below.', actionLabel: 'Write a post', recoveryLabel: 'Return to default', recoverTo: 'default', kind: 'empty', busy: false, blocksPrimary: true, requiresAcknowledgement: false), 'error': ProofStateFixture(title: 'We could not finish that', body: 'Review the highlighted information and try again.', actionLabel: 'Write a post', recoveryLabel: 'Return to default', recoverTo: 'default', kind: 'error', busy: false, blocksPrimary: true, requiresAcknowledgement: false), 'success': ProofStateFixture(title: 'All set', body: 'The example moved to its local compose state.', actionLabel: 'Composer opened', recoveryLabel: 'Return to default', recoverTo: null, kind: 'success', busy: false, blocksPrimary: false, requiresAcknowledgement: false), 'focused': ProofStateFixture(title: 'Input focused', body: 'The active field stays visible above the keyboard.', actionLabel: 'Write a post', recoveryLabel: 'Return to default', recoverTo: null, kind: 'interaction', busy: false, blocksPrimary: false, requiresAcknowledgement: false), 'enabled': ProofStateFixture(title: 'Action ready', body: 'The primary action is ready for this local example.', actionLabel: 'Write a post', recoveryLabel: 'Return to default', recoverTo: null, kind: 'interaction', busy: false, blocksPrimary: false, requiresAcknowledgement: false)},
};
